# Generated by Django 3.2 on 2022-04-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20220430_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='url',
        ),
        migrations.AddField(
            model_name='blogimage',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
